lib/ros/be/application/services/templates/services/fluentd/etc/config.d/cloud_events.conf.erb
=> [WHIS-8] Add fluentd config for cloudevents to kafka

lib/ros/be/application/services/files/helm-charts/cp-helm-charts/cp-schema-registry/.helmignore, lib/ros/be/application/services/files/helm-charts/cp-helm-charts/cp-schema-registry/Chart.yaml, lib/ros/be/application/services/files/helm-charts/cp-helm-charts/cp-schema-registry/README.md, lib/ros/be/application/services/files/helm-charts/cp-helm-charts/cp-schema-registry/templates/NOTES.txt, lib/ros/be/application/services/files/helm-charts/cp-helm-charts/cp-schema-registry/templates/_helpers.tpl, lib/ros/be/application/services/files/helm-charts/cp-helm-charts/cp-schema-registry/templates/deployment.yaml, lib/ros/be/application/services/files/helm-charts/cp-helm-charts/cp-schema-registry/templates/jmx-configmap.yaml, lib/ros/be/application/services/files/helm-charts/cp-helm-charts/cp-schema-registry/templates/service.yaml, lib/ros/be/application/services/files/helm-charts/cp-helm-charts/cp-schema-registry/values.yaml, lib/ros/be/application/services/files/helm-charts/cp-helm-charts/cp-zookeeper/.helmignore, lib/ros/be/application/services/files/helm-charts/cp-helm-charts/cp-zookeeper/Chart.yaml, lib/ros/be/application/services/files/helm-charts/cp-helm-charts/cp-zookeeper/README.md, lib/ros/be/application/services/files/helm-charts/cp-helm-charts/cp-zookeeper/templates/NOTES.txt, lib/ros/be/application/services/files/helm-charts/cp-helm-charts/cp-zookeeper/templates/_helpers.tpl, lib/ros/be/application/services/files/helm-charts/cp-helm-charts/cp-zookeeper/templates/headless-service.yaml, lib/ros/be/application/services/files/helm-charts/cp-helm-charts/cp-zookeeper/templates/jmx-configmap.yaml, lib/ros/be/application/services/files/helm-charts/cp-helm-charts/cp-zookeeper/templates/poddisruptionbudget.yaml, lib/ros/be/application/services/files/helm-charts/cp-helm-charts/cp-zookeeper/templates/service.yaml, lib/ros/be/application/services/files/helm-charts/cp-helm-charts/cp-zookeeper/templates/statefulset.yaml, lib/ros/be/application/services/files/helm-charts/cp-helm-charts/cp-zookeeper/values.yaml, lib/ros/be/application/services/templates/skaffold/kafkastack.yml.erb
Hi Duan, 
Please review initial commit of kafkastack template.
Still can't get working relative chartPath for zookeeper and schema-registry. Will need your advice on that.
UPD chartPath actually works...
So next step would be to update generator.rb to pull `cp-helm-charts` repo, right?
=> Devops whistler

lib/ros/be/application/services/generator.rb, lib/ros/be/application/services/templates/services/fluentd/etc/config.d/ros.conf.erb
Fluentd config changes to test iam-> fluentd-> kafka data flow
=> Fluentd -> Kafka config changes

lib/ros/be/infra/cli.rb, lib/ros/be/infra/files/terraform/gcp/gci/main.tf, lib/ros/be/infra/files/terraform/gcp/gci/outputs.tf, lib/ros/be/infra/files/terraform/gcp/gci/variables.tf, lib/ros/be/infra/files/terraform/gcp/vpc/main.tf, lib/ros/be/infra/files/terraform/gcp/vpc/outputs.tf, lib/ros/be/infra/files/terraform/gcp/vpc/variables.tf, lib/ros/be/infra/generator.rb, lib/ros/be/infra/templates/terraform/gcp/instance.tf.erb
Hi Guys, 
PLease review and allow merge for GCP terraform templates
=> Initial GCP terraform templates

lib/ros/be/application/cli/kubernetes.rb, lib/ros/be/application/services/templates/skaffold/kafka-connect.yml.erb, lib/ros/be/application/services/templates/skaffold/kafka-schema-registry.yml.erb, lib/ros/be/application/services/templates/skaffold/kafka-zookeeper.yml.erb, lib/ros/be/application/services/templates/skaffold/kafka.yml.erb
=> Fix podLabels for kafkastack

lib/ros/be/application/services/files/helm-charts/cp-helm-charts/cp-kafka-connect/templates/deployment.yaml, lib/ros/be/application/services/files/helm-charts/cp-helm-charts/cp-schema-registry/templates/deployment.yaml, lib/ros/be/application/services/files/helm-charts/cp-helm-charts/cp-zookeeper/templates/statefulset.yaml
Hi Duan, small change to cp-charts to support pod labels
=> Add podLabel support to cp kafka charts

lib/ros/be/application/cli/kubernetes.rb
Config structure same as for other services. I.e.
kafka
config:
enabled:no
=> Check whether service is enabled or not before deploy them to k8s

lib/ros/be/application/cli.rb, lib/ros/be/application/cli/kubernetes.rb
Add "skip-infra" cmd argument that will skip deploy any infra services
=> Add "skip-infra" cmd argument

lib/ros/be/application/cli.rb
Add --enabled services/platform key to ros be list command
=> Add --enabled services/platform key to ros be list command

lib/ros/be/infra/files/terraform/gcp/gci/main.tf, lib/ros/be/infra/files/terraform/gcp/gci/templates/startup-script.tpl, lib/ros/be/infra/files/terraform/gcp/gci/variables.tf, lib/ros/be/infra/files/terraform/gcp/vpc/main.tf, lib/ros/be/infra/files/terraform/gcp/vpc/outputs.tf, lib/ros/be/infra/templates/terraform/gcp/instance.tf.erb
Updated GCP terraform templates. 
Startup script file added.
=> Updated GCP terraform templates, startup script file

lib/ros/main/env/templates/environments.yml.erb
`aws_account_id` and `aws_default_region`
=> Add aws account and region to envs

lib/ros/be/application/platform/files/helm-charts/service/templates/deployment.yaml, lib/ros/be/application/platform/files/helm-charts/service/templates/service.yaml, lib/ros/be/application/platform/files/helm-charts/service/values.yaml, lib/ros/be/application/platform/templates/skaffold/service.yml.erb
Works. Prometheus can get the metrics from sidecar.
=> [WHIS-14] Add prometheus exporter sidecar

lib/ros/be/application/services/generator.rb, lib/ros/be/infra/files/terraform/aws/eks-resources/files/get_alb_arn.py, lib/ros/be/infra/files/terraform/aws/eks-resources/files/grafana-ingress/.helmignore, lib/ros/be/infra/files/terraform/aws/eks-resources/files/grafana-ingress/Chart.yaml, lib/ros/be/infra/files/terraform/aws/eks-resources/files/grafana-ingress/README.md, lib/ros/be/infra/files/terraform/aws/eks-resources/files/grafana-ingress/templates/_helpers.tpl, lib/ros/be/infra/files/terraform/aws/eks-resources/files/grafana-ingress/templates/gateway.yaml, lib/ros/be/infra/files/terraform/aws/eks-resources/files/grafana-ingress/templates/virtual-service.yaml, lib/ros/be/infra/files/terraform/aws/eks-resources/files/grafana-ingress/values.yaml, lib/ros/be/infra/files/terraform/aws/eks-resources/files/grafana/dashboards/1-dash_rails_app_overview.json, lib/ros/be/infra/files/terraform/aws/eks-resources/files/grafana/datasources/1-prometheus.yaml, lib/ros/be/infra/files/terraform/aws/eks-resources/main.tf, lib/ros/be/infra/files/terraform/aws/eks-resources/templates/grafana/helm-grafana-ingress.tpl, lib/ros/be/infra/files/terraform/aws/eks-resources/templates/grafana/helm-grafana.tpl, lib/ros/be/infra/files/terraform/aws/eks-resources/variables.tf, lib/ros/be/infra/generator.rb, lib/ros/be/infra/templates/terraform/aws/kubernetes.tf.erb
[WHIS-29] Terraform templates changes accordingly to whistler production.yml refactor
=> [WHIS-29] Terraform templates changes accordingly to whistler production.yml refactor

lib/ros/be/application/cli/kubernetes.rb, lib/ros/be/application/services/generator.rb, lib/ros/main/env/generator.rb
Read gcp bigquery svc account key from encrypted config file (cfg file pushed to whistler)
=> [WHIS-32] Read gcp bigquery svc account key from config file

lib/ros/be/application/cli/kubernetes.rb
HI Duan, 
Please merge this small fix. 
JSON string needs to be surrounded by single quotes
=> [WHIS-32] Properly quote literal json string

lib/ros/be/infra/files/terraform/aws/eks-resources/files/fluentd/Chart.yaml, lib/ros/be/infra/files/terraform/aws/eks-resources/files/fluentd/templates/daemonset.yaml, lib/ros/be/infra/files/terraform/aws/eks-resources/main.tf
=> [WHIS-45] Add fluentd log rotation

lib/ros/be/infra/files/terraform/aws/eks-resources/files/fluentd/Chart.yaml, lib/ros/be/infra/files/terraform/aws/eks-resources/files/fluentd/templates/configmap.yaml
Hi Duan, 
I've updated fluentd config buffer section to match current syntax.
=> [WHIS-45] Update fluentd-gcp conf to 1.x syntax

lib/ros/main/project/templates/config/deployment.yml
Update deployment.yml template
=> [WHIS-52] Update deployment.yml template

lib/ros/be/application/cli.rb
Version auto increment implemented for `ros be deploy tag`
=> [WHIS-54] Version auto increment

lib/ros/be/application/services/templates/services/fluentd/etc/config.d/ros.conf.erb, lib/ros/be/application/services/templates/skaffold/kafka-connect.yml.erb, lib/ros/be/infra/files/terraform/aws/eks-resources/main.tf, lib/ros/be/infra/files/terraform/aws/eks-resources/templates/grafana/helm-grafana.tpl, lib/ros/be/infra/files/terraform/aws/eks-resources/variables.tf, lib/ros/be/infra/generator.rb, lib/ros/be/infra/templates/terraform/aws/kubernetes.tf.erb, lib/ros/main/project/files/config/deployments/development.yml, lib/ros/main/project/templates/config/deployment.yml
[WHIS-37] Add external google authentication for grafana
[WHIS-28] Pass istio settings from config as helm configutaionOverrides
[WHIS-47] Log faulty fluentd messages. This will help debugging fluentd message flow
=> Add external google authentication for grafana, istio configurable

lib/ros/be/infra/files/terraform/aws/s3/main.tf, lib/ros/be/infra/files/terraform/aws/s3/variables.tf, lib/ros/be/infra/generator.rb, lib/ros/be/infra/templates/terraform/aws/kubernetes.tf.erb
=> [WHIS-60] Create S3 bucket TF code

lib/ros/be/application/generator.rb, lib/ros/be/application/services/generator.rb, lib/ros/be/application/services/templates/jobs/kafka-connect/connector-provision-job.yml.erb
[WHIS-24] Generate avro subjects from service avro schema files
=> [WHIS-24] Generate avro subjects from service avro schema files

lib/ros/be/infra/files/terraform/aws/cloudfront-s3/main.tf, lib/ros/be/infra/files/terraform/aws/cloudfront-s3/variables.tf, lib/ros/be/infra/files/terraform/aws/eks-cluster/main.tf, lib/ros/be/infra/files/terraform/aws/eks-cluster/variables.tf, lib/ros/be/infra/files/terraform/aws/s3/main.tf, lib/ros/be/infra/files/terraform/aws/s3/outputs.tf, lib/ros/be/infra/templates/terraform/aws/kubernetes.tf.erb
[WHIS-63] Add s3 read/write permissions to eks worker node
=> [WHIS-63] Add s3 read/write permissions to eks worker node

lib/ros/be/application/platform/templates/compose/service.yml.erb
We need this config so we can generate files inside the sre folder.
=> [PW-1883] Add sre folder to root path

lib/ros/be/application/cli/kubernetes.rb, lib/ros/be/infra/templates/terraform/aws/kubernetes.tf.erb
* Update tiller_image to v2.15.0
* Revert to update helm repos just once during k8s deploy
=> Update tiller version

lib/ros/be/application/platform/rails/core/rails/templates/config/sidekiq.yml.tt
* No ticket
Get rid of queue names except `"#{Settings.service.name}_default"`.
=> Consolidate queues names

lib/ros/be/application/services/generator.rb, lib/ros/be/application/services/templates/services/fluentd/etc/config.d/ros.conf.erb
=> [PW-1975] Fluentd config to stream HTTP logs to BQ

lib/ros/be/application/cli.rb, lib/ros/be/application/cli/instance.rb, lib/ros/be/application/cli_base.rb
Also added `rspec_options` option to test command.
=> [PW-2131] Add copy_service_file command to copy files from container to local

lib/ros/be/application/services/templates/jobs/fluentd/kafka-topic-creation-job.yml.erb
Fix kafka topic creation grep to exact match
=> Fix kafka topic creation grep

lib/ros/be/application/services/templates/jobs/fluentd/kafka-topic-creation-job.yml.erb
Final fix for kafka topic creation
=> Fix kafka topic creation

lib/ros/be/application/cli/kubernetes.rb
This is to address avro schema changes between releases.
Kafka topic creation job and kafka-connect sink connector update job should be launched on every deploy.
=> Update ros be up to run infra services migration jobs every deploy

lib/ros/be/application/platform/templates/skaffold/service.yml.erb
Add default PDB minAvailable=1 for platform services skaffold
=> Add default PDB minAvailable=1 for platform services skaffold

lib/ros/be/application/cli/kubernetes.rb
Skip flag to be respected by infra jobs to prevent those run in parallel on CI
=> Skip flag to be respected by infra jobs

lib/ros/be/application/generator.rb
=> PW 2292 - Fix api endpoint generation

lib/ros/be/infra/files/terraform/aws/eks-resources/files/grafana/dashboards/2-rails_app_overview.json, lib/ros/be/infra/files/terraform/aws/eks-resources/files/grafana/dashboards/3-worker_jobs.json, lib/ros/be/infra/files/terraform/aws/eks-resources/templates/grafana/helm-grafana.tpl, lib/ros/be/infra/files/terraform/aws/eks-resources/templates/helm-victoria-metrics.tpl
Update grafana dashboards, adjust monitoring stack resources assignments
=> Update grafana dashboards, adjust monitoring stack resources assignments

lib/ros/be/application/platform/templates/skaffold/service.yml.erb, lib/ros/be/infra/files/terraform/aws/eks-cluster/main.tf, lib/ros/be/infra/files/terraform/aws/eks-cluster/variables.tf, lib/ros/be/infra/files/terraform/aws/eks-resources/main.tf, lib/ros/be/infra/files/terraform/aws/eks-resources/templates/helm-fluentd-gcp.tpl, lib/ros/be/infra/generator.rb, lib/ros/be/infra/templates/terraform/aws/kubernetes.tf.erb
This will enable app services to prefer deployment on spot instances (if exist)
This will affect UAT environment only
=> PW-2316 implement spot instances uat

lib/ros/be/infra/files/terraform/aws/eks-resources/files/grafana/dashboards/8-cluster_usage_overview.json, lib/ros/be/infra/files/terraform/aws/eks-resources/files/grafana/dashboards/9-pod_resource_usage_by_node.json
=> Update Grafana dashboards

lib/ros/be/infra/files/terraform/aws/eks-resources/main.tf, lib/ros/be/infra/templates/terraform/aws/kubernetes.tf.erb
=> Minor terraform updates

lib/ros/be/infra/files/terraform/aws/eks-resources/files/grafana/dashboards/4-loki_application_logs.json, lib/ros/be/infra/files/terraform/aws/eks-resources/files/grafana/dashboards/5-containter_resource_usage.json
Grafana dashboards minor updates
=> Grafana dashboards minor updates

lib/ros/be/infra/files/terraform/aws/cloudfront-s3/main.tf, lib/ros/be/infra/files/terraform/aws/eks-cluster/main.tf, lib/ros/be/infra/files/terraform/aws/eks-resources/files/cert-manager/README.md, lib/ros/be/infra/files/terraform/aws/eks-resources/files/cert-manager/certificaterequests.yaml, lib/ros/be/infra/files/terraform/aws/eks-resources/files/cert-manager/certificates.yaml, lib/ros/be/infra/files/terraform/aws/eks-resources/files/cert-manager/challenges.yaml, lib/ros/be/infra/files/terraform/aws/eks-resources/files/cert-manager/clusterissuers.yaml, lib/ros/be/infra/files/terraform/aws/eks-resources/files/cert-manager/issuers.yaml, lib/ros/be/infra/files/terraform/aws/eks-resources/files/cert-manager/orders.yaml, lib/ros/be/infra/files/terraform/aws/eks-resources/main.tf, lib/ros/be/infra/files/terraform/aws/eks-resources/variables.tf, lib/ros/be/infra/generator.rb, lib/ros/be/infra/templates/terraform/aws/kubernetes.tf.erb, lib/ros/stack.rb
This PR adds support for cert-manager and its related CRDs.
Also fixes some minor issues related to production cluster launch.
Let's discuss tmrw.
=> [PW-2529] Terraform. Add cert-manager and related CRDs

lib/ros/be/infra/files/terraform/aws/cloudfront-s3/main.tf, lib/ros/be/infra/files/terraform/aws/eks-cluster/main.tf, lib/ros/be/infra/files/terraform/aws/eks-resources/main.tf, lib/ros/be/infra/files/terraform/aws/rds/main.tf, lib/ros/be/infra/files/terraform/aws/rds/variables.tf, lib/ros/be/infra/files/terraform/aws/route53/main.tf, lib/ros/be/infra/files/terraform/aws/route53/outputs.tf, lib/ros/be/infra/templates/terraform/aws/kubernetes.tf.erb
Terraform. Minor fixes to allow launch new environment
=> [PW-2532] Terraform. Minor fixes to allow launch new environment

lib/ros/be/application/services/templates/skaffold/kafka-connect.yml.erb, lib/ros/be/application/services/templates/skaffold/kafka-schema-registry.yml.erb
Add pod affitity/tolerations for kafka connect-ui, schema-registry-ui
Let those components to run on spot instances
=> Add pod affitity/tolerations for kafka connect-ui, schema-registry-ui

lib/ros/be/application/platform/templates/skaffold/service.yml.erb
Set recreatePods:false to eliminate services downtime during upgrade
Minor cleanup `services.yml.erb`
=> [PW-2655] Set recreatePods:false to eliminate services downtime during upgrade

lib/ros/be/application/generator.rb
Fix DNS domain name generation if subdomain is nil/empty
=> [PW-2532] Fix DNS domain name generation if subdomain is nil/empty

lib/ros/be/application/platform/generator.rb, lib/ros/be/application/platform/templates/skaffold/service.yml.erb
[Add HPA and make config for resources and replica min/max configurable for whistler-services](https://perxtechnologies.atlassian.net/browse/PW-2585)
Add support to get HPA configuration from config file
=> [PW-2585] Add support for HPA configuration

lib/ros/be/infra/templates/terraform/aws/kubernetes.tf.erb
=> [PW-2735] Terraform. Add SES module

lib/ros/be/application/services/templates/skaffold/kafka-connect.yml.erb, lib/ros/be/application/services/templates/skaffold/kafka-schema-registry.yml.erb, lib/ros/be/application/services/templates/skaffold/kafka-zookeeper.yml.erb, lib/ros/be/application/services/templates/skaffold/kafka.yml.erb, lib/ros/be/application/services/templates/skaffold/postgres.yml.erb, lib/ros/be/application/services/templates/skaffold/redis.yml.erb
Skaffold. Set wait: true to infra services
This should help to successfully launch new namespace from using CI
=> Skaffold. Set wait: true to infra services

lib/ros/be/application/cli/kubernetes.rb, lib/ros/cli_base.rb, lib/ros/data/bqview/cli.rb, lib/ros/data/metabase/cli.rb
Add error catch for TF commands
=> Add error catch for TF commands

lib/ros/be/infra/generator.rb, lib/ros/be/infra/templates/terraform/aws/kubernetes.tf.erb, lib/ros/cli_base.rb, lib/ros/data/metabase/cli.rb
* Use kubectl provider to manage CRDs
* Minor changes to custom providers download
=> [PW-3193] Use kubectl provider for CRDs

lib/ros/be/infra/templates/terraform/aws/kubernetes.tf.erb
=> [PW-3193] Cleanup.
