exe/ros
lib/ros.rb
lib/ros/be/application/cli.rb
lib/ros/be/application/cli/generate.rb
lib/ros/be/application/cli/instance.rb
lib/ros/be/application/cli/kubernetes.rb
lib/ros/be/application/cli_base.rb
lib/ros/be/application/platform/generator.rb
lib/ros/be/application/platform/rails/service/app/initializers.rb
lib/ros/be/application/platform/rails/service/plugin/templates/lib/%namespaced_name%/engine.rb.tt
lib/ros/be/infra/cli.rb
lib/ros/cli_base.rb
lib/ros/main/env/generator.rb
lib/ros/postman/open_api.rb

This mostly solves the problem of attribute errors being undefined when running: `ros be infra init -l`

Move errors to CliBase

---

lib/ros/be/application/cli/kubernetes.rb
lib/ros/be/application/services/generator.rb
lib/ros/be/application/services/templates/jobs/kafka-connect/connector-provision-job.yml.erb
lib/ros/main/env/generator.rb

Hi Guys, 
This pull request is adding support for k8s Jobs. Kafka-connect connectors provisioning job is added as a first example.
Job templates are to be placed in services/templates/jobs/$service_name/ folder.
Another thing I've tried to address with this pull request:
With current implementation there is no way to update running infra service. If service is already running and has correct name labels assigned - it just silently skipped. I.e. `ros be up kafka` will do nothing if kafka already running.
Firstly I thought just to add `option.force`, but it also triggers force update for other resources, that may not be required.
So I tried to separate application services (platform and core) from infra services, accordingly to their declaration in config files. And implement unbreaking …

Update to k8s services deployment. Add support for Jobs. Add kafka-connectors provision job template

---

lib/ros/be/infra/cli.rb
lib/ros/be/infra/cluster/generator.rb
lib/ros/be/infra/files/terraform/aws/eks-cluster/main.tf
lib/ros/be/infra/templates/terraform/aws/kubernetes.tf.erb

Hi Duan, 
This PR address following issues:
1. Fix `dns.(sub)domain` references in `kubernetes.erb.tf`
2. Temporary commented  null-resource `k8s-tiller-rbac` dependancy on eks module. It caused me circular dependancy with `module.eks-cluster.module.eks.aws_launch_configuration.workers` when I launched `ros be infra apply` on existing cluster and it planned to update worker nodes config (volumes 50G -> 100G). 
I'm not sure if this dependancy is necessary, as  `k8s-tiller-rbac` triggered when kubeconfig file is ready...Does that implies that cluster is ready as well??
I'll keep it in mind and have a closer look when launching cluster infra from scratch
3. `ros be infra init` updated to consider AWS profile when getting and updating user kubeconfig
Precedence as following:
a. ENV …

Refactor ros init

---

lib/ros/be/application/services/files/helm-charts/cp-helm-charts/cp-kafka-connect/templates/deployment.yaml
lib/ros/be/application/services/templates/jobs/kafka-connect/connector-provision-job.yml.erb
lib/ros/be/application/services/templates/skaffold/kafka-connect.yml.erb
lib/ros/be/application/services/templates/skaffold/kafka-schema-registry.yml.erb

Hi Duan, 
The issue with kafka-connect connectors provisioning started at the time we got dev1 namespace launched. Two kafka-connect servers in different namespaces, but using same connector name. So their connectors groupId had the same value. That confused all instances of kafka-connect running in different namespaces, but working with same external confluent kafka cluster. I've added feature_set suffix to connector name. That fixed an issue.
I believe the same should be done for kafka topics as a part of [WHIS-24](https://perxtechnologies.atlassian.net/browse/WHIS-24).

[WHIS-22] Fix kafka connector provisioning job

---

lib/ros/be/application/generator.rb

Set feature_set from ROS_FS env.
If ROS_FS empty - use `components.be.components.application.config.feature_set`

[WHIS-52] Set feature_set from ROS_FS env

---

lib/ros/be/application/platform/templates/skaffold/service.yml.erb

Hi Duan,
There is a tiny fix for non-ros services prometheus_exporter path.
Tested that it generates correct skaffold files. You can safely merge it. But don't enable metrics collection yet. There is another issue I've reported to Rob.

[WHIS-44] Fix prometheus_exporter path for non-ros services

---

lib/ros/be/application/platform/templates/skaffold/service.yml.erb

All non-ros services should run `bundle exec -C config/sidekiq.yml` instead of `bundle exec -r spec/dummy -C config/sidekiq.yml`

Fix worker command for non-ros OSS services

---

lib/ros/be/application/platform/templates/skaffold/service.yml.erb
lib/ros/be/application/services/templates/skaffold/kafka-schema-registry.yml.erb

* Add `app:ros:avro:register` task to service bootstrap if `kafka-schema-registry` enabled in config
* Fix erb failure if `kafka_schema_registry.ui` not defined

[PW-1847] Add avro:register task to service bootstrap

---

lib/ros/be/application/cli/kubernetes.rb
lib/ros/be/application/platform/templates/skaffold/service.yml.erb
lib/ros/be/application/services/templates/jobs/kafka-connect/connector-provision-job.yml.erb

Hi Duan, 
Couple changes:
* Create avro schemas upon migration job run
* Allow to re-create gcp service account key if cli option `force`
* KAfka-connect set `autoUpdateSchemas = true`

Add kafka schema registry schemas create during bootstrap job

---

lib/ros/be/application/cli_base.rb

Currently when we run `ros be test` this will try to run rubocop for the ros project.
1. From a ros-cli perspective this should not be default behaviour because the choice of using rubocop should be made by each project development group
2. Running the rubocop within the service does not actually lint all our files because we are currently loading ros-core and ros-sdk as libs but hey are not linted individually.
3. Waiting for the images to be built to be able to run the lint is counter productive.
4. At most we could provide a separate command that would invoke rubocop directly without building the image, but that seems useless

[Chore] Remove rubocop from the commands being run with test

---

lib/ros/be/application/platform/generator.rb
lib/ros/be/application/platform/templates/skaffold/service.yml.erb

Example of generated env vars for uat master:
```
env | grep SEN
SENTRY_ENVIRONMENT=production-uat
SENTRY_RELEASE=0.1.0-development-9c66d4fe
SENTRY_DSN=https://<<censored>>@sentry.io/1819291
```

[PW-2460] Add Sentry environment vars to platform services

---

lib/ros/be/application/cli.rb

In order to disable auto deploy to staging, I suggest to implement `push by tag` strategy , same as we use for deploy to UAT
`ros be deploy staging` will create and push a tag `staging.v1` that we can match on CircleCi and deploy accordingly.
same for `ros be deploy production`

[PW-2468] Extend ros be deploy to staging/production

---

lib/ros/be/application/cli/kubernetes.rb

Currently we have `platform.env` secret created/deleted in parallel by multiple CI containers. That gives us false negative build results when two or more containers trying to delete the secret at the same time.
Suggest to respect `--skip-infra` flag when updating platform secret, so secret create/delete will be handled by first CI container only.

Fix platform secret creation by CI

---

lib/ros/be/application/platform/templates/skaffold/service.yml.erb

Disable Pod Disruption Budget for `scheduler` profile.
Any PDBs that already been created will have to delete manually.

[PW-2493] Disable PDB for scheduler profile

---

lib/ros/be/application/platform/templates/skaffold/service.yml.erb

Reduce default resource requests by platform services
Next step would be to set resource requests by environment and by service in config file.

Reduce default resource requests by platform services

---

lib/ros/be/application/cli/kubernetes.rb
lib/ros/be/application/platform/templates/skaffold/service.yml.erb

[Upgrade skaffold to v1](https://perxtechnologies.atlassian.net/browse/PW-2463)
This PR makes `ros be up` compatible with skaffold v1.
Following commands tested against skaffold v1.0.1:
`ros be up ${service}`
`ros be up ${service} -b`
`ros be build ${service}`
However, there is no backward compatibility with skaffold v0.38.0 we currently using in ros-cli. So should be merged together with following [setup repo PR](https://github.com/rails-on-services/setup/pull/10) and ros-cli image to be rebuilt.

[PW-2463] Upgrade skaffold build/deploy to comply with Skaffold V1

---

lib/ros/be/application/cli/kubernetes.rb
lib/ros/be/application/platform/templates/skaffold/service.yml.erb

Enable horizontal pod autoscaler for service/worker profiles.
Respective service helm chart was updated by [this commit](https://github.com/rails-on-services/helm-charts/commit/b1ed4cdb8e85ef293d151c4b985b125c2b423326) . Pls review also

[PW-2585] Enable horizontal pod autoscaler for service/worker profiles

---

lib/ros/be/infra/templates/terraform/aws/kubernetes.tf.erb

This PR creates and assign IAM policy to list/get cloudwatch mentrics by cluster nodes. Used for Grafana Cloudwatch provider.

PW-2457/add redis dashboards to grafana

---

lib/ros/be/infra/cli.rb

Add `--clear` flag to `infra` command to force terraform reload registry modules

Add --clear flag to infra command to force terraform reload registry modules

---

Gemfile.lock
ros.gemspec

If we try to load the cli from a bundle that already contains other ROS pieces, we will get a conflict on rake as they all require 13.

rake: 12 -> 13

---

lib/ros/be/application/cli.rb
lib/ros/be/application/cli/kubernetes.rb
lib/ros/be/application/platform/templates/skaffold/service.yml.erb

`--atomic` flag to let helm roll back failed deployment install/upgrade
`--only-infra`  flag to be able launch only infra services for new deployments, so services bootstrap jobs won't fail if infra not in ready state yet.

[PW-2796] Add --atomic flag to helm install/upgrade. Add --only-infra cli command flag

---

lib/ros/be/application/services/generator.rb
lib/ros/be/application/services/templates/jobs/fluentd/kafka-topic-creation-job.yml.erb
lib/ros/be/application/services/templates/jobs/kafka-connect/connector-provision-job.yml.erb

This PR makes kafka-connect BigQuery connectors separated by service name.
In current setup there are 82 topics processed by single connector, one topic failure brings down whole kafka-to-BigQuery pipeline.

[PW-2966] Split kafka-connect BQ connectors by service name

---

lib/ros/be/application/services/templates/skaffold/postgres.yml.erb

Current official postgres chart installs PostGIS extensions by default.
We don't need to use 3rd party docker image for that anymore, as it is outdated and uses it's own config files that we cannot override with stable helm chart.

Postgres skaffold - use official bitnami image

---

lib/ros/be/application/platform/templates/skaffold/service.yml.erb
lib/ros/be/application/services/templates/skaffold/kafka-connect.yml.erb
lib/ros/be/application/services/templates/skaffold/kafka-schema-registry.yml.erb

* Set application service template podAntiAffinity to `preferred`.
This will address the case when auto-scaler wasn't able to schedule new pods. With `required` podAntiAffinity we basically restricted by current number of running nodes 
* Set podAnnotations to kafka services to allow Prometheus successfully scrape metrics.

Update skaffold templates

---

lib/ros/be/application/cli/instance.rb

following error thrown by CircleCi recently:
`Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"rails\": executable file not found in $PATH": unknown`
This PR should fix that

Fix rails path for docker-composer

---

lib/ros/be/application/platform/templates/skaffold/service.yml.erb
lib/ros/be/infra/templates/terraform/aws/kubernetes.tf.erb

This is to separate avro schemas migration job from DB migration job.
Should be easier to debug migrations. Faulty schemas won't affect DB migration and vice versa.
Also added variable into `kubernetes.tf.erb` to respect RDS instance size from config.
Update to service helm-chart is [here](https://github.com/rails-on-services/helm-charts/commit/ac0f7fa227de6f2c666c5086fa79252cc2a07704)

Separate avro schemas and database migrations in two jobs
